version: "3"

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
#      DEBUG: 1
      SQL_ENGINE: "django.db.backends.postgresql"
      SQL_DATABASE: "databaseName"
      SQL_USER: "yourPostgresUsername"
      SQL_PASSWORD: "yourPassword"
      SQL_HOST: "db"
      CELERY_BROKER_URL: "redis://redis:6379"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "databaseName"
      POSTGRES_USER: "yourPostgresUsername"
      POSTGRES_PASSWORD: "yourPassword"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgres_data: