# Generated by Django 4.1.4 on 2023-01-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producer',
            new_name='Studio',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='producer',
            new_name='studio',
        ),
    ]
