# Generated by Django 4.1.4 on 2023-01-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_rename_producer_studio_rename_producer_anime_studio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='type_anime',
            new_name='kind',
        ),
    ]
