# Generated by Django 4.1.4 on 2023-01-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_rename_type_anime_anime_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('anons', 'Announced'), ('ongoing', 'Airing'), ('released', 'Finished')], max_length=50),
        ),
    ]
