# Generated by Django 4.1.4 on 2023-01-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_anime_episodes_review_status_review_watched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watched',
            new_name='watched_episodes',
        ),
    ]
