# Generated by Django 4.1.4 on 2023-01-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_rename_watched_review_watched_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='watched_episodes',
            field=models.IntegerField(default=0),
        ),
    ]
