# Generated by Django 4.1.4 on 2023-01-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0012_alter_anime_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('Planned to Watch', 'Planned To Watch'), ('Completed', 'Completed'), ('Dropped', 'Dropped'), ('On Hold', 'On Hold'), ('Re-watching', 'Re Watching'), ('Watching', 'Watching')], default='Completed', max_length=50),
        ),
    ]
