# Generated by Django 4.1.4 on 2023-01-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_alter_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned To Watch'), ('watching', 'Watching'), ('rewatching', 'Rewatching'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped')], default='completed', max_length=50),
        ),
    ]
