# Generated by Django 4.1.4 on 2023-01-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0014_alter_review_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
    ]
